### ISSUE TITLE
Can't Ctrl+D to exit egsh

### ISSUE THREAD

**Issue by sandbergja** [kcls/evergreen-universe-rs#13]
This is the absolute smallest inconvenience ever.  If I am in `srfsh` and want to exit, I can just press `Ctrl + D`.  However, when I am in `egsh`, `Ctrl + D` doesn't do the trick, I have to type exit, quit, or stop.

If it's okay, I'd be interested in taking a look at this to see if I can figure out how to implement this.

**Comment by berick** [comment]
Yes, that would be a useful addition.
