### ISSUE TITLE
Rewrite authority_authority_linker.pl as a bin crate

### ISSUE THREAD

**Issue by sandbergja** [kcls/evergreen-universe-rs#15]
As a way to get more practice with Rust (and maybe even get some performance gains), I was thinking of rewriting Evergreen's [authority_authority_linker.pl](https://github.com/evergreen-library-system/Evergreen/blob/main/Open-ILS/src/support-scripts/authority_authority_linker.pl.in) in Rust, keeping the behavior and command line args the same.

How does that sound, @berick ?

**Comment by berick** [comment]
Sounds great!

I'm sure you've already seen it, but you could pull a lot of boilerplate from https://github.com/kcls/evergreen-universe-rs/blob/main/kcls/src/bin/bib-to-auth-linker.rs  

In particular, ScriptUtil and the getops stuff.  (Note I'm planning to tweak ScriptUtil::init() to make the parameters more explicit / extensible).

Let me know if I can help with anything.

**Comment by sandbergja** [comment]
Oh, nice!  Thanks for pointing out `ScriptUtil`.

When you're working on `ScriptUtil::init()` -- would there be any option to pass in some arbitrary command line args, rather than what comes from `std::env::args()`?  My immediate use case is for writing some tests, it would be great to be able to supply, say, my own `Vec<String>` and make assertions about how it behaves with this or that command-line arg.  Or maybe there's a good way to do this already... let me know what you think!

**Comment by berick** [comment]
Along the lines of this?  

https://github.com/kcls/evergreen-universe-rs/commit/bf7b36453b64feb15c34a1d1f22c297d38dc890c#diff-611eb5f4bce023b642417707f166b65b202119be4d9c0d1b7938294e285785cb

See `extra_params`

Includes some other tweaks, re-branding to script::Runner, etc.

**Comment by sandbergja** [comment]
I love it!  Thanks so much, @berick !

**Comment by berick** [comment]
Great, merged to main.
