### ISSUE TITLE
Publish the MARC library to crates.io

### ISSUE THREAD

**Issue by berick** [kcls/evergreen-universe-rs#19]
I'm considering publishing the MARC portion of this repository to crates.io.

There's already a MARC library on crates -- https://crates.io/crates/marc -- which I have experimented with.  It's is a bit more low-level / Rusty and does not, as far as I can tell, include XML and breaker support.  The MARC library in this repository, on the other hand, is meant to be more utilitarian and possibly easier for users new to Rust.  

It just needs a name.  One thought was "marcutf8" since it's primarily a String shuffling library.

**Comment by sandbergja** [comment]
I think this would be very useful -- the MarcXML support in particular would be very useful.  I'm bad at naming libraries, so I have no feedback on that.

**Comment by berick** [comment]
Thanks for the feedback, @sandbergja.

I opted to publish under the generic name "marctk" (MARC Toolkit):  https://crates.io/crates/marctk

And now it's clear I need to expand on the documentation :)
